default_stages: [commit]

repos:
  - repo: https://github.com/mssalvatore/merge-issue-number-hook
    rev: v1.0.0
    hooks:
      - id: merge-issue-number
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
